/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/product.glb 
*/

import React from 'react'
import { useGLTF, MeshTransmissionMaterial, useTexture } from '@react-three/drei'

export default function Product({ customColor, materialType, ...props }) {
  
  const { nodes, materials } = useGLTF('/product.glb')

  const woodTexture = useTexture('/wood-diffuse.png')


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.material.geometry} rotation={[Math.PI / 2, 0, 0]} >

        {/* CONDITION 1: Standard Plastic (Uses the color picker) */}
        {materialType === 'plastic' && (
          <meshStandardMaterial color={customColor} roughness={0.4} metalness={0} />
        )}

        {/* CONDITION 2: Shiny Metal (Ignores color, sets high metalness) */}
        {materialType === 'metal' && (
          <meshStandardMaterial color="#cccccc" roughness={0.1} metalness={1} />
        )}

        {/* CONDITION 3: Textured Wood (Applies the image we loaded) */}
        {materialType === 'wood' && (
          <meshStandardMaterial map={woodTexture} roughness={0.6} />
        )}

        {/* CONDITION 4: Realistic Glass (Uses meshPhysicalMaterial for advanced optics) */}
        {materialType === 'glass' && (
          <meshPhysicalMaterial 
            transmission={1} // Acts like glass
            opacity={1}
            transparent
            roughness={0}
            ior={1.5} // Index of refraction
            thickness={0.5}
          />
        )}

      </mesh>
    </group>
  )
}

useGLTF.preload('/product.glb')
useTexture.preload('/wood-diffuse.png')
