/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/t6.glb 
*/
import * as THREE from 'three'
import React, { useMemo, useEffect } from 'react'
import { useGLTF, MeshTransmissionMaterial, useTexture } from '@react-three/drei'

export default function T6Component({ seatColor, floorMaterialType, ...props }) {

  const group = React.useRef()

  const { nodes, materials, animations } = useGLTF('/wireframes/t6.glb')

/////////////////////////////////////////////////////////////
  // SEAT MATERIALS
  /////////////////////////////////////////////////////////////

  // 1. Load the Tan Leather textures
  const tanLeather = useTexture({
    map: '/maps/upholstery/UPHOLSTREY.2_001_Base Color.jpeg',
    normalMap: '/maps/upholstery/UPHOLSTREY.2_001_Normal.jpeg',
    aoMap: '/maps/upholstery/UPHOLSTREY.2_001_Ambient Occlusion.jpeg'
  })

  // Configure tan leather textures once
  useMemo(() => {
    tanLeather.map.colorSpace = THREE.SRGBColorSpace
    Object.values(tanLeather).forEach((texture) => {
      texture.wrapS = THREE.RepeatWrapping
      texture.wrapT = THREE.RepeatWrapping
      texture.repeat.set(2.3, 2.3) // Adjust this to scale the leather grain
    })
  }, [tanLeather])

  // Create your dynamic material with textures baked in (stable reference)
  const customSeatMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({ 
      ...tanLeather, // Automatically applies the map, normalMap, and aoMap!
      roughness: 2, // Leather isn't super shiny
      metalness: 0
    })
  }, [tanLeather])

  // Update color dynamically without recreating material
  useEffect(() => {
    customSeatMaterial.color.set(seatColor || '#ffffff')
  }, [seatColor, customSeatMaterial])

  /////////////////////////////////////////////////////////////
  //FLOOR MATERIALS
  /////////////////////////////////////////////////////////////

  // 1. Load the checkboard texture
  const checkFloor = useTexture({
    map: '/maps/floor/Floor_008_Base Color.jpeg',
    normalMap: '/maps/floor/Floor_008_Normal.jpeg',
    aoMap: '/maps/floor/Floor_008_Ambient Occlusion.jpeg'
  })
  
  useMemo(() => {
    checkFloor.map.colorSpace = THREE.SRGBColorSpace
    Object.values(checkFloor).forEach((texture) => {
      texture.wrapS = THREE.RepeatWrapping
      texture.wrapT = THREE.RepeatWrapping
      texture.repeat.set(.5, .5) 
    })
  }, [checkFloor])


  // 1. Load the wood texture
  const oakFloor = useTexture({
    map: '/maps/floor/Floor_007_Base Color.jpeg',
    normalMap: '/maps/floor/Floor_007_Normal.jpeg',
    aoMap: '/maps/floor/Floor_007_Ambient Occlusion.jpeg'
  })
  
  useMemo(() => {
    oakFloor.map.colorSpace = THREE.SRGBColorSpace
    Object.values(oakFloor).forEach((texture) => {
      texture.wrapS = THREE.RepeatWrapping
      texture.wrapT = THREE.RepeatWrapping
      texture.repeat.set(.5, .5) 

      // Rotate 90 degrees (Math.PI / 2 radians)
      // If you need it to go the other way, just use -Math.PI / 2
      texture.rotation = Math.PI / 2 

      // VERY IMPORTANT: Tell it to spin from the center, not the corner!
      texture.center.set(0.5, 0.5)
    })
  }, [oakFloor])


  // 1. Load the stone texture
  const stoneFloor = useTexture({
    map: '/maps/floor/Floor_005_Base Color.jpeg',
    normalMap: '/maps/floor/Floor_005_Normal.jpeg',
    aoMap: '/maps/floor/Floor_005_Ambient Occlusion.jpeg'
  })
  
  useMemo(() => {
    stoneFloor.map.colorSpace = THREE.SRGBColorSpace
    Object.values(stoneFloor).forEach((texture) => {
      texture.wrapS = THREE.RepeatWrapping
      texture.wrapT = THREE.RepeatWrapping
      texture.repeat.set(1, 1) 
    })
  }, [stoneFloor])

  // Select the active floor textures based on selection
  const activeFloorTextures = useMemo(() => {
    if (floorMaterialType === 'checkboard') return checkFloor
    if (floorMaterialType === 'oak') return oakFloor
    if (floorMaterialType === 'stone') return stoneFloor
    return null
  }, [floorMaterialType, checkFloor, oakFloor, stoneFloor])

  

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Uplight" position={[-0.591, 1.245, -1.117]} scale={0.001}>
          <group name="Uplight001" position={[0.354, -0.765, 0]} />
        </group>
        <group name="Shape003" position={[-0.14, 1.393, -2.128]} rotation={[1.309, 0, -Math.PI]} scale={-0.001} />
        <group name="Shape002" position={[-0.14, 1.393, -2.128]} rotation={[1.309, 0, -Math.PI]} scale={-0.001} />
        <group name="Shape001" position={[-0.14, 0.909, -1.794]} scale={0.001} />
        <group name="Stitch_Line" position={[-0.054, 1.393, -2.13]} rotation={[1.309, 0, -Math.PI]} scale={-0.001} />
        <group name="Conversion_001" position={[0.149, 1.191, -1.649]} scale={0.001}>
          <group name="Conversion" position={[-528.618, -0.642, 527.893]}>
            <group name="Cupboard_001" position={[186.702, -488.873, 147.902]}>
              <mesh name="Cupboard_front_001" geometry={nodes.Cupboard_front_001.geometry} material={materials['WHITE GLOSS']} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials.Stainless_Steel_Dull} position={[-4.701, 67.779, 133.205]} />
              <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials.Stainless_Steel_Dull} position={[-4.701, -112.135, 133.205]} />
              <mesh name="Object002" geometry={nodes.Object002.geometry} material={materials.PSTRIP_002} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Push_button_001" geometry={nodes.Push_button_001.geometry} material={materials.Stainless_Steel_Dull} position={[6.12, 92.999, -83.59]} rotation={[0, 0, -Math.PI / 2]} />
            </group>
            <group name="Cupboard_004" position={[26.848, 639.731, -136.235]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Cupboard_front_004" geometry={nodes.Cupboard_front_004.geometry} material={materials['WHITE GLOSS']} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Cylinder009" geometry={nodes.Cylinder009.geometry} material={materials.Stainless_Steel_Dull} position={[-4.701, 140.003, 133.205]} />
              <mesh name="Cylinder010" geometry={nodes.Cylinder010.geometry} material={materials.Stainless_Steel_Dull} position={[-4.701, -112.135, 133.205]} />
              <mesh name="Object023" geometry={nodes.Object023.geometry} material={materials.PSTRIP_002} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Push_button_004" geometry={nodes.Push_button_004.geometry} material={materials.Stainless_Steel_Dull} position={[6.12, 41.936, 17.724]} rotation={[0, 0, -Math.PI / 2]} />
            </group>
            <group name="Cupboard_006" position={[166.149, -30.623, -715.277]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Cupboard_front_006" geometry={nodes.Cupboard_front_006.geometry} material={materials['WHITE GLOSS']} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Cylinder013" geometry={nodes.Cylinder013.geometry} material={materials.Standard} position={[-4.701, 206.714, 133.205]} />
              <mesh name="Cylinder014" geometry={nodes.Cylinder014.geometry} material={materials.Standard} position={[-4.701, 35.315, 133.205]} />
              <mesh name="Object011" geometry={nodes.Object011.geometry} material={materials.PSTRIP_002} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Push_button_006" geometry={nodes.Push_button_006.geometry} material={materials.Stainless_Steel_Dull} position={[6.12, 152.761, 17.724]} rotation={[0, 0, -Math.PI / 2]} />
            </group>
            <group name="Cupboard_007" position={[127.034, 479.024, -1535.417]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Cupboard_front_007" geometry={nodes.Cupboard_front_007.geometry} material={materials['WHITE GLOSS']} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Cylinder015" geometry={nodes.Cylinder015.geometry} material={materials.Stainless_Steel_Dull} position={[-4.701, -35.109, 393.35]} rotation={[Math.PI / 2, 0, 0]} />
              <mesh name="Cylinder016" geometry={nodes.Cylinder016.geometry} material={materials.Stainless_Steel_Dull} position={[-4.701, -35.109, -14.987]} rotation={[Math.PI / 2, 0, 0]} />
              <mesh name="Object028" geometry={nodes.Object028.geometry} material={materials.PSTRIP_002} position={[-0.68, 0, -1.798]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Push_button_007" geometry={nodes.Push_button_007.geometry} material={materials.Stainless_Steel_Dull} position={[6.12, 265.461, 39.482]} rotation={[0, 0, -Math.PI / 2]} />
            </group>
            <group name="Cupboard_008" position={[725.172, -491.304, -435.242]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
              <mesh name="Cupboard_front_008" geometry={nodes.Cupboard_front_008.geometry} material={materials['WHITE GLOSS']} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Object005" geometry={nodes.Object005.geometry} material={materials.PSTRIP_002} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Push_button_008" geometry={nodes.Push_button_008.geometry} material={materials.Stainless_Steel_Dull} position={[6.12, 54.008, -7.632]} rotation={[0, 0, -Math.PI / 2]} />
            </group>
            <group name="Cupboard_009" position={[186.702, -488.873, -167.331]} rotation={[0, 0, -Math.PI]} scale={-1}>
              <mesh name="Cupboard_front_009" geometry={nodes.Cupboard_front_009.geometry} material={materials['WHITE GLOSS']} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Cylinder030" geometry={nodes.Cylinder030.geometry} material={materials.Stainless_Steel_Dull} position={[-4.701, 67.778, 133.205]} />
              <mesh name="Cylinder031" geometry={nodes.Cylinder031.geometry} material={materials.Stainless_Steel_Dull} position={[-4.701, -112.135, 133.205]} />
              <mesh name="Object003" geometry={nodes.Object003.geometry} material={materials.PSTRIP_002} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Push_button_009" geometry={nodes.Push_button_009.geometry} material={materials.Stainless_Steel_Dull} position={[6.12, 92.999, -83.59]} rotation={[0, 0, -Math.PI / 2]} />
            </group>
            <group name="Cupboard_010" position={[26.849, 639.692, -695.431]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Cupboard_front_010" geometry={nodes.Cupboard_front_010.geometry} material={materials['WHITE GLOSS']} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Cylinder032" geometry={nodes.Cylinder032.geometry} material={materials.Standard} position={[-4.701, 206.714, 133.205]} />
              <mesh name="Cylinder033" geometry={nodes.Cylinder033.geometry} material={materials.Standard} position={[-4.701, 35.315, 133.205]} />
              <mesh name="Object012" geometry={nodes.Object012.geometry} material={materials.PSTRIP_002} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Push_button_010" geometry={nodes.Push_button_010.geometry} material={materials.Stainless_Steel_Dull} position={[6.12, 152.761, 17.723]} rotation={[0, 0, -Math.PI / 2]} />
            </group>
            <group name="Cupboard_011" position={[26.848, 639.731, 413.228]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Cupboard_front_011" geometry={nodes.Cupboard_front_011.geometry} material={materials['WHITE GLOSS']} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Cylinder034" geometry={nodes.Cylinder034.geometry} material={materials.Stainless_Steel_Dull} position={[-4.701, 140.003, 133.205]} />
              <mesh name="Cylinder035" geometry={nodes.Cylinder035.geometry} material={materials.Stainless_Steel_Dull} position={[-4.701, -112.135, 133.205]} />
              <mesh name="Object024" geometry={nodes.Object024.geometry} material={materials.PSTRIP_002} position={[-0.68, 0, -1.799]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Push_button_011" geometry={nodes.Push_button_011.geometry} material={materials.Stainless_Steel_Dull} position={[6.12, 41.936, 17.723]} rotation={[0, 0, -Math.PI / 2]} />
            </group>
            <group name="DownLight_001" position={[-52.214, 452.865, 566.072]}>
              <group name="Downlight_001" position={[0.049, -6.137, -0.055]} rotation={[0, 0, Math.PI]} scale={0.701}>
                <group name="Circle6074" position={[0, -2.521, 0]} />
                <mesh name="Circle6075" geometry={nodes.Circle6075.geometry} material={materials['Material #2142149786']} position={[0, -0.001, 0]} />
                <mesh name="Circle6076" geometry={nodes.Circle6076.geometry} material={materials.Blk_LightD} position={[0, 0.317, 0]} />
                <mesh name="Sphere46517" geometry={nodes.Sphere46517.geometry} material={materials.Spotlight_Bulb} position={[0.117, -1.83, 0.045]} rotation={[0, 0, -Math.PI]} scale={[1, 0.186, 1]} />
              </group>
              <mesh name="Object030" geometry={nodes.Object030.geometry} material={materials.PSTRIP_002} position={[0.217, 10, 0]} rotation={[0, 0, -Math.PI]} />
              <mesh name="Shelf_Light_001" geometry={nodes.Shelf_Light_001.geometry} material={materials['CAPPUCCINO MATTE']} position={[0.217, 10, 0]} rotation={[0, 0, Math.PI]} />
            </group>
            <group name="DownLight_004" position={[-52.214, 452.865, 3.316]}>
              <group name="Downlight_006" position={[0.049, -6.137, -0.055]} rotation={[0, 0, Math.PI]} scale={0.701}>
                <group name="Circle6083" position={[0, -2.521, 0]} />
                <mesh name="Circle6084" geometry={nodes.Circle6084.geometry} material={materials['Material #2142149786']} position={[0, -0.001, 0]} />
                <mesh name="Circle6085" geometry={nodes.Circle6085.geometry} material={materials.Blk_LightD} position={[0, 0.317, 0]} />
                <mesh name="Sphere46520" geometry={nodes.Sphere46520.geometry} material={materials.Spotlight_Bulb} position={[0.117, -1.83, 0.045]} rotation={[0, 0, -Math.PI]} scale={[1, 0.186, 1]} />
              </group>
              <mesh name="Object031" geometry={nodes.Object031.geometry} material={materials.PSTRIP_002} position={[0.217, 10, 0]} rotation={[0, 0, -Math.PI]} />
              <mesh name="Shelf_Light_004" geometry={nodes.Shelf_Light_004.geometry} material={materials['CAPPUCCINO MATTE']} position={[0.217, 10, 0]} rotation={[0, 0, Math.PI]} />
            </group>
            <group name="DownLight_005" position={[-52.214, 452.865, -558.652]}>
              <group name="Downlight_007" position={[0.049, -6.137, -0.055]} rotation={[0, 0, Math.PI]} scale={0.701}>
                <group name="Circle6086" position={[0, -2.521, 0]} />
                <mesh name="Circle6087" geometry={nodes.Circle6087.geometry} material={materials['Material #2142149786']} position={[0, -0.001, 0]} />
                <mesh name="Circle6088" geometry={nodes.Circle6088.geometry} material={materials.Blk_LightD} position={[0, 0.317, 0]} />
                <mesh name="Sphere46521" geometry={nodes.Sphere46521.geometry} material={materials.Spotlight_Bulb} position={[0.117, -1.83, 0.045]} rotation={[0, 0, -Math.PI]} scale={[1, 0.186, 1]} />
              </group>
              <mesh name="Object032" geometry={nodes.Object032.geometry} material={materials.PSTRIP_002} position={[0.217, 10, 0]} rotation={[0, 0, -Math.PI]} />
              <mesh name="Shelf_Light_005" geometry={nodes.Shelf_Light_005.geometry} material={materials['CAPPUCCINO MATTE']} position={[0.217, 10, 0]} rotation={[0, 0, Math.PI]} />
            </group>
            <group name="Fridge001" position={[204.993, -392.375, 526.108]}>
              <mesh name="Box008" geometry={nodes.Box008.geometry} material={materials.Rubber} position={[-0.154, 272.501, 186.714]} />
              <mesh name="Box009" geometry={nodes.Box009.geometry} material={materials.Rubber} position={[-5.078, 272.038, -11.047]} />
              <mesh name="Box010" geometry={nodes.Box010.geometry} material={materials.Rubber} position={[-0.154, 272.501, -186.259]} />
              <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials.Rubber} position={[13.928, 277.039, 187.207]} />
              <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials.Rubber} position={[12.508, 298.658, -186.74]} />
              <mesh name="Fridge" geometry={nodes.Fridge.geometry} material={materials['WHITE GLOSS']} position={[-24.846, -2.8, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Object" geometry={nodes.Object.geometry} material={materials.PSTRIP_002} position={[-24.846, -2.8, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
            </group>
            <group name="Oven001" position={[91.706, -122.252, -12.011]}>
              <mesh name="Box027" geometry={nodes.Box027.geometry} material={materials.Stainless_Steel_Dull_Dark} position={[99.093, 73.058, 19.918]} scale={[2.039, 1.23, 1]} />
              <mesh name="Cylinder021" geometry={nodes.Cylinder021.geometry} material={materials.Powder_Coated_black} position={[85.479, -74.458, -187.409]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Cylinder022" geometry={nodes.Cylinder022.geometry} material={materials.Powder_Coated_black} position={[85.479, 42.021, -185.961]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.721} />
              <mesh name="Cylinder023" geometry={nodes.Cylinder023.geometry} material={materials.Stainless_Steel_Dull_Dark} position={[84.186, 73.456, 128.414]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Cylinder024" geometry={nodes.Cylinder024.geometry} material={materials.Stainless_Steel_Dull_Dark} position={[84.186, 73.456, -89.292]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Line005" geometry={nodes.Line005.geometry} material={materials.Stainless_Steel_Dull} position={[78.718, -104.802, 19.722]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Line006" geometry={nodes.Line006.geometry} material={materials.Powder_Coated_black} position={[85.399, -45.673, -185.051]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Line007" geometry={nodes.Line007.geometry} material={materials.Stainless_Steel_Dull} position={[85.269, -136.831, -0.182]} rotation={[Math.PI / 2, 0, 0]} />
              <mesh name="Line008" geometry={nodes.Line008.geometry} material={materials.Stainless_Steel_Dull} position={[85.269, -83.14, -220.05]} rotation={[-Math.PI, 0, 0]} />
              <mesh name="Line009" geometry={nodes.Line009.geometry} material={materials.Stainless_Steel_Dull} position={[83.096, 101.331, 0.215]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <group name="Oven" position={[45.114, -18.903, -34.187]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
                <mesh name="Mesh055" geometry={nodes.Mesh055.geometry} material={materials.Stainless_Steel_Dull} />
                <mesh name="Mesh055_1" geometry={nodes.Mesh055_1.geometry} material={materials.Vray_ShinyGlass} />
              </group>
              <mesh name="Oven001_1" geometry={nodes.Oven001_1.geometry} material={materials.Standard} position={[-51.54, -18.903, -34.187]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Oven_Trays" geometry={nodes.Oven_Trays.geometry} material={materials.Stainless_Steel_Dull} position={[-28.26, 24.712, -7.111]} rotation={[0, 1.571, 0]} scale={[781.36, 781.36, 1117.633]} />
              <mesh name="Screw_001" geometry={nodes.Screw_001.geometry} material={materials.Stainless_Steel_Dull} position={[87.56, -133.726, 190.791]} scale={[1.281, 0.488, 1.281]} />
              <mesh name="Screw_002" geometry={nodes.Screw_002.geometry} material={materials.Stainless_Steel_Dull} position={[87.56, -133.726, -175.516]} scale={[1.281, 0.488, 1.281]} />
              <mesh name="Screw_003" geometry={nodes.Screw_003.geometry} material={materials.Stainless_Steel_Dull} position={[87.528, -88.044, -217.009]} rotation={[Math.PI / 2, 0, 0]} scale={[1.281, 0.488, 1.281]} />
              <mesh name="Screw_004" geometry={nodes.Screw_004.geometry} material={materials.Stainless_Steel_Dull} position={[87.528, 74.807, -217.009]} rotation={[Math.PI / 2, 0, 0]} scale={[1.281, 0.488, 1.281]} />
            </group>
            <group name="Pole" position={[185.87, 5.551, 206.637]}>
              <group name="Line004" position={[0.387, -0.074, -0.168]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Box025" geometry={nodes.Box025.geometry} material={materials['Grey/blue_Plastic']} position={[-6.111, 0.075, 517.839]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 0.845, 0.696]} />
              <mesh name="Box026" geometry={nodes.Box026.geometry} material={materials['Grey/blue_Plastic']} position={[-6.111, 0.075, -497.194]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[-1, -0.845, -0.696]} />
              <mesh name="Cylinder017" geometry={nodes.Cylinder017.geometry} material={materials.Rubber} position={[-1.951, 0.069, 524.364]} rotation={[Math.PI / 2, 0, -1.484]} />
              <mesh name="Cylinder018" geometry={nodes.Cylinder018.geometry} material={materials.Rubber} position={[6.086, 0.036, 478.263]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh name="Cylinder019" geometry={nodes.Cylinder019.geometry} material={materials.Rubber} position={[6.086, 0.036, -457.618]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-1} />
              <mesh name="Cylinder020" geometry={nodes.Cylinder020.geometry} material={materials.Rubber} position={[-1.951, 0.069, -503.719]} rotation={[-Math.PI / 2, 0, 1.658]} scale={-1} />
            </group>
            <group name="Sink" position={[-40.296, 163.603, 361.161]}>
              <group name="Line017" position={[66.94, -116.212, -221.163]} rotation={[Math.PI / 2, 0, -Math.PI / 4]} />
              <group name="Line018" position={[-20.362, -116.212, -133.86]} rotation={[Math.PI / 2, 0, 2.356]} />
              <group name="Line019" position={[66.94, -116.212, -133.86]} rotation={[Math.PI / 2, 0, Math.PI / 4]} />
              <group name="Line020" position={[-20.362, -116.212, -221.163]} rotation={[Math.PI / 2, 0, -2.356]} />
              <group name="Line021" position={[67.477, -116.212, -332.533]} rotation={[Math.PI / 2, 0, Math.PI / 4]} />
              <group name="Line022" position={[-19.825, -116.212, -419.836]} rotation={[Math.PI / 2, 0, -2.356]} />
              <group name="Line023" position={[67.477, -116.212, -419.836]} rotation={[Math.PI / 2, 0, -Math.PI / 4]} />
              <group name="Line024" position={[-19.825, -116.212, -332.533]} rotation={[Math.PI / 2, 0, 2.356]} />
              <group name="Rounded_Sink" position={[26.746, -164.258, -75.035]}>
                <mesh name="Box036" geometry={nodes.Box036.geometry} material={materials.Stainless_Steel_Dull} position={[-1.001, 26.719, 3.609]} />
                <mesh name="Object049" geometry={nodes.Object049.geometry} material={materials.Stainless_Steel_Dull} position={[-3.571, 24.318, 216.654]} />
              </group>
              <group name="Sink_Covers" position={[-151.921, -105.551, -46.97]}>
                <group name="Untitled001" position={[5.306, 100.698, 49.159]} />
                <mesh name="Box032" geometry={nodes.Box032.geometry} material={materials.Black_Wood} position={[-1.49, 139.571, 169.016]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                <mesh name="Box033" geometry={nodes.Box033.geometry} material={materials.Black_Wood} position={[-1.49, 139.571, -70.699]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={-1} />
                <mesh name="Cylinder026" geometry={nodes.Cylinder026.geometry} material={materials.Rubber} position={[7.346, 23.577, 325.752]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                <mesh name="Cylinder027" geometry={nodes.Cylinder027.geometry} material={materials.Rubber} position={[7.346, 23.577, 98.771]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                <mesh name="Cylinder028" geometry={nodes.Cylinder028.geometry} material={materials.Rubber} position={[7.346, 23.577, -416.392]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                <mesh name="Cylinder029" geometry={nodes.Cylinder029.geometry} material={materials.Rubber} position={[7.346, 23.577, -9.648]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                <mesh name="Line010" geometry={nodes.Line010.geometry} material={materials.Stainless_Steel_Dull} position={[5.739, 21.448, 328.03]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                <mesh name="Line011" geometry={nodes.Line011.geometry} material={materials.Stainless_Steel_Dull} position={[5.739, 21.448, 101.049]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                <mesh name="Line012" geometry={nodes.Line012.geometry} material={materials.Stainless_Steel_Dull} position={[5.739, 21.448, -414.114]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
                <mesh name="Line013" geometry={nodes.Line013.geometry} material={materials.Stainless_Steel_Dull} position={[5.739, 21.448, -7.37]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              </group>
              <group name="Cooker_Hob_001" position={[22.85, -129.505, -177.593]} rotation={[0, 0, Math.PI]} scale={[-0.727, -0.842, -0.727]}>
                <mesh name="Mesh091" geometry={nodes.Mesh091.geometry} material={materials.Powder_Coated_black} />
                <mesh name="Mesh091_1" geometry={nodes.Mesh091_1.geometry} material={materials.Powder_Coated_black} />
                <mesh name="Mesh091_2" geometry={nodes.Mesh091_2.geometry} material={materials.Stainless_Steel_Dull} />
              </group>
              <group name="Cooker_Hob_002" position={[23.506, -129.505, -375.35]} rotation={[0, 0, Math.PI]} scale={[-0.727, -0.842, -0.727]}>
                <mesh name="Mesh092" geometry={nodes.Mesh092.geometry} material={materials.Powder_Coated_black} />
                <mesh name="Mesh092_1" geometry={nodes.Mesh092_1.geometry} material={materials.Powder_Coated_black} />
                <mesh name="Mesh092_2" geometry={nodes.Mesh092_2.geometry} material={materials.Stainless_Steel_Dull} />
              </group>
              <mesh name="Tap" geometry={nodes.Tap.geometry} material={materials.Stainless_Steel_Polished} position={[-65.421, -126.386, 313.468]} rotation={[0, -Math.PI / 9, 0]} />
            </group>
            <mesh name="Tall_Cupboard_side_trim" geometry={nodes.Tall_Cupboard_side_trim.geometry} material={materials.PSTRIP_002} position={[-229.661, -337.489, -774.981]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
            <mesh name="Box012upper_Cupboard_side_" geometry={nodes.Box012upper_Cupboard_side_.geometry} material={materials['WHITE GLOSS']} position={[-114.466, 339.977, 774.981]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
            <group name="Box014" position={[2.62, 469.527, 2.123]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
              <mesh name="Mesh008" geometry={nodes.Mesh008.geometry} material={materials['CAPPUCCINO MATTE']} />
              <mesh name="Mesh008_1" geometry={nodes.Mesh008_1.geometry} material={materials['BABY BLUE GLOSS']} />
            </group>
            <mesh name="Box015" geometry={nodes.Box015.geometry} material={materials['WHITE GLOSS']} position={[150.857, -335.191, -848.455]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
            <group name="Box016" position={[-33.116, -337.489, -564.375]} rotation={[-Math.PI, 0, -Math.PI / 2]}>
              <mesh name="Mesh033" geometry={nodes.Mesh033.geometry} material={materials.P_Stirp_001} />
              <mesh name="Mesh033_1" geometry={nodes.Mesh033_1.geometry} material={materials.PSTRIP_002} />
              <mesh name="Mesh033_2" geometry={nodes.Mesh033_2.geometry} material={materials.PSTRIP_003} />
            </group>
            <mesh name="Box018" geometry={nodes.Box018.geometry} material={materials.Standard} position={[-223.394, -335.191, 257.101]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
            <mesh name="Box028" geometry={nodes.Box028.geometry} material={materials['EBONY GLOSS WORKTOP']} position={[-231.216, 79.867, -5.037]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
            <group name="Camper_Logo" position={[180.041, -66.969, 525.683]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
              <mesh name="Mesh006" geometry={nodes.Mesh006.geometry} material={materials.Stainless_Steel_Dull} />
              <mesh name="Mesh006_1" geometry={nodes.Mesh006_1.geometry} material={materials.Stainless_Steel_Dull_Logo} />
            </group>
            <group name="Counter_Top" position={[-20.063, 30.2, 6.224]}>
              <mesh name="Mesh003" geometry={nodes.Mesh003.geometry} material={materials['EBONY GLOSS WORKTOP']} />
              <mesh name="Mesh003_1" geometry={nodes.Mesh003_1.geometry} material={materials['LEATHER WORKTOP']} />
            </group>
            <mesh name="Cylinder025" geometry={nodes.Cylinder025.geometry} material={materials.Rubber} position={[-35.99, 380.837, -763.413]} rotation={[Math.PI / 2, 0, 0]} />
            <mesh name="Kitchen_Front" geometry={nodes.Kitchen_Front.geometry} material={materials['WHITE GLOSS']} position={[165.235, -335.191, 257.101]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
            <group name="Kitchen_Side" position={[-229.661, -337.489, 767.776]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
              <mesh name="Mesh105" geometry={nodes.Mesh105.geometry} material={materials['WHITE GLOSS']} />
              <mesh name="Mesh105_1" geometry={nodes.Mesh105_1.geometry} material={materials['SEA GRASS FUR']} />
            </group>
            <group name="Kitchen_Side_2" position={[-229.661, -337.489, -352.671]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
              <mesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials['CAPPUCCINO MATTE']} />
              <mesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials['CHROME YELLOW GLOSS']} />
            </group>
            <mesh name="Kitchen_side_trim" geometry={nodes.Kitchen_side_trim.geometry} material={materials.PSTRIP_002} position={[-229.661, -337.489, 767.776]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
            <mesh name="Kitchen_Side_trim_2" geometry={nodes.Kitchen_Side_trim_2.geometry} material={materials.PSTRIP_002} position={[-229.661, -337.489, -352.671]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
            <mesh name="Object009" geometry={nodes.Object009.geometry} material={materials.PSTRIP_002} position={[384.072, -555.942, -448.371]} rotation={[0, 1.571, 0]} />
            <mesh name="Object014" geometry={nodes.Object014.geometry} material={materials.PSTRIP_002} position={[-77.539, 693.217, -983.991]} rotation={[Math.PI, 0, -Math.PI / 2]} />
            <group name="Socket_Base" position={[-49.428, 301.009, -775.7]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Mesh078" geometry={nodes.Mesh078.geometry} material={materials['24 - Default']} />
              <mesh name="Mesh078_1" geometry={nodes.Mesh078_1.geometry} material={materials.Grey_Dull_plastic} />
            </group>
            <group name="Socket_Base001" position={[-49.428, 207.459, -775.7]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="Mesh077" geometry={nodes.Mesh077.geometry} material={materials['24 - Default']} />
              <mesh name="Mesh077_1" geometry={nodes.Mesh077_1.geometry} material={materials.Grey_Dull_plastic} />
            </group>
            <mesh name="Tall_Cupboard_front" geometry={nodes.Tall_Cupboard_front.geometry} material={materials['WHITE GLOSS']} position={[106.696, -335.191, -1282.854]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
            <mesh name="Tall_Cupboard_side" geometry={nodes.Tall_Cupboard_side.geometry} material={materials['WHITE GLOSS']} position={[-229.661, -337.489, -774.981]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
            <mesh name="Tall_Cupboard_top" geometry={nodes.Tall_Cupboard_top.geometry} material={materials['WHITE GLOSS']} position={[-77.539, 693.217, -983.991]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
            <mesh name="under_seat" geometry={nodes.under_seat.geometry} material={materials['WHITE GLOSS']} position={[384.072, -555.942, -448.371]} rotation={[0, 1.571, 0]} />
            <mesh name="Under_seat_Back" geometry={nodes.Under_seat_Back.geometry} material={materials.Standard} position={[384.072, -555.942, -912.895]} rotation={[0, 1.571, 0]} />
            <mesh name="Under_seat_Front" geometry={nodes.Under_seat_Front.geometry} material={materials['WHITE GLOSS']} position={[763.409, -486.454, -438.097]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh name="Under_seat_Trim" geometry={nodes.Under_seat_Trim.geometry} material={materials.PSTRIP_002} position={[763.409, -486.454, -438.097]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
            <mesh name="upper_Cupboard" geometry={nodes.upper_Cupboard.geometry} material={materials['WHITE GLOSS']} position={[16.228, 583.46, 2.123]} rotation={[Math.PI / 2, 0, Math.PI]} />
            <mesh name="upper_Cupboard_side_trim" geometry={nodes.upper_Cupboard_side_trim.geometry} material={materials.PSTRIP_002} position={[-114.465, 339.977, 774.981]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
            <mesh name="upper_Cupboard_trim" geometry={nodes.upper_Cupboard_trim.geometry} material={materials.PSTRIP_002} position={[16.228, 583.46, 2.123]} rotation={[Math.PI / 2, 0, Math.PI]} />
          </group>

          
         <group name="Seats" position={[208.72, 45.363, -226.252]}>
            <group name="ALL_BLACK_LEATHER_SEATS" position={[-75.019, -13.771, 2.155]}>
              
              {/* SEATBELTS: Left exactly as they were */}
              <group name="Seatbelt" position={[-87.402, -32.96, -195.571]} rotation={[-0.262, 0, 0]}>
                <mesh name="Line002" geometry={nodes.Line002.geometry} material={materials.Plastic} position={[3.237, 123.504, 55.179]} rotation={[Math.PI / 2, 0, 0]} scale={0.866} />
                <mesh name="SeatBelt_001" geometry={nodes.SeatBelt_001.geometry} material={materials.Seatbelt} position={[0.484, 161.412, -1.746]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              </group>
              <group name="Seatbelt001" position={[88.896, -32.96, -195.571]} rotation={[-0.262, 0, 0]}>
                <mesh name="Line003" geometry={nodes.Line003.geometry} material={materials.Plastic} position={[3.237, 123.416, 55.68]} rotation={[Math.PI / 2, 0, 0]} scale={0.866} />
                <mesh name="SeatBelt_002" geometry={nodes.SeatBelt_002.geometry} material={materials.Seatbelt} position={[0.484, 161.412, -1.746]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
              </group>

              {/* STITCHES: Left exactly as they were */}
              <mesh name="DoubleStitch_013" geometry={nodes.DoubleStitch_013.geometry} material={materials.Stitch_LIME} position={[-94.853, 27.969, -191.351]} rotation={[1.309, 0, Math.PI]} scale={-1} />
              <mesh name="DoubleStitch_020" geometry={nodes.DoubleStitch_020.geometry} material={materials.Stitch_LIME} position={[94.427, 27.969, -191.352]} rotation={[-1.833, 0, Math.PI]} />

              {/* THE SEATS: Prop replaced with `customSeatMaterial` */}
              <mesh name="Seat_Part_022" geometry={nodes.Seat_Part_022.geometry} material={customSeatMaterial} position={[288.5, -309.652, 79.415]} rotation={[-Math.PI, 0, 0]} scale={-1} />
              <mesh name="Object038" geometry={nodes.Object038.geometry} material={customSeatMaterial} position={[-337.472, 169.93, -256.589]} rotation={[1.309, 0, -Math.PI]} scale={-1} />
              <mesh name="Object045" geometry={nodes.Object045.geometry} material={customSeatMaterial} position={[-337.472, 169.93, -256.589]} rotation={[1.309, 0, -Math.PI]} scale={-1} />
              <mesh name="Object050" geometry={nodes.Object050.geometry} material={customSeatMaterial} position={[337.472, 169.93, -256.589]} rotation={[-1.833, 0, -Math.PI]} />
              <mesh name="Object052" geometry={nodes.Object052.geometry} material={customSeatMaterial} position={[337.472, 169.93, -256.589]} rotation={[-1.833, 0, -Math.PI]} />
              <mesh name="Seat_Part_001" geometry={nodes.Seat_Part_001.geometry} material={customSeatMaterial} position={[-423.302, -314.282, 79.415]} />
              <mesh name="Seat_Part_002" geometry={nodes.Seat_Part_002.geometry} material={customSeatMaterial} position={[-288.5, -309.652, 79.415]} />
              <mesh name="Seat_Part_003" geometry={nodes.Seat_Part_003.geometry} material={customSeatMaterial} position={[10.221, -314.282, 79.415]} />
              <mesh name="Seat_Part_006" geometry={nodes.Seat_Part_006.geometry} material={customSeatMaterial} position={[-423.302, 169.931, -253.985]} rotation={[1.309, 0, -Math.PI]} scale={-1} />
              
              <group name="Seat_Part_012" position={[-337.472, 169.93, -256.589]} rotation={[1.309, 0, -Math.PI]} scale={-1}>
                <mesh name="Mesh146" geometry={nodes.Mesh146.geometry} material={customSeatMaterial} />
                <mesh name="Mesh146_1" geometry={nodes.Mesh146_1.geometry} material={materials.SIMORA} />
                <mesh name="Mesh146_2" geometry={nodes.Mesh146_2.geometry} material={materials['TITANIUM GRID']} />
                <mesh name="Mesh146_3" geometry={nodes.Mesh146_3.geometry} material={materials['STANDARD BRICK']} />
              </group>
              
              <mesh name="Seat_Part_016" geometry={nodes.Seat_Part_016.geometry} material={customSeatMaterial} position={[-45.833, 169.931, -253.985]} rotation={[1.309, 0, -Math.PI]} scale={-1} />
              
              <group name="Seat_Part_023" position={[337.472, 169.93, -256.589]} rotation={[-1.833, 0, Math.PI]}>
                <mesh name="Mesh133" geometry={nodes.Mesh133.geometry} material={customSeatMaterial} />
                <mesh name="Mesh133_1" geometry={nodes.Mesh133_1.geometry} material={materials.SIMORA} />
                <mesh name="Mesh133_2" geometry={nodes.Mesh133_2.geometry} material={materials['TITANIUM GRID']} />
                <mesh name="Mesh133_3" geometry={nodes.Mesh133_3.geometry} material={materials['STANDARD BRICK']} />
              </group>
              
              <mesh name="Seat_Part_024" geometry={nodes.Seat_Part_024.geometry} material={customSeatMaterial} position={[423.302, 169.931, -253.985]} rotation={[-1.833, 0, Math.PI]} />
              <mesh name="Seat_Part_025" geometry={nodes.Seat_Part_025.geometry} material={customSeatMaterial} position={[423.302, -314.282, 79.415]} rotation={[Math.PI, 0, 0]} scale={-1} />
            </group>

            
            
            <mesh name="DoubleStitch_001" geometry={nodes.DoubleStitch_001.geometry} material={materials.Stitch_Cream} position={[-336.445, -319.732, -375.089]} />
            <mesh name="DoubleStitch_006" geometry={nodes.DoubleStitch_006.geometry} material={materials.Stitch_Cream} position={[179.232, -319.732, -401.773]} />
          </group>


          <group name="Untitled" position={[0, -64.475, 21.256]} />


          <mesh
          name="Floor"
          geometry={nodes.Floor.geometry}
          position={[-149.389, -701.901, 4.993]}
          rotation={[Math.PI / 2, 0, 0]}
          >
        {/* 4. DROP YOUR MATERIAL LOGIC INSIDE */}

        {activeFloorTextures && (
          <meshStandardMaterial 
            {...activeFloorTextures} 
            roughness={2} 
            aoMapIntensity={1} 
          />
        )}

      </mesh>

        </group>
        <group name="VRayCam001Target" position={[-3.672, 0.111, -2.831]} scale={0.001} />
        <group name="VRayCam001" position={[1.352, 1.588, -0.621]} rotation={[1.463, 0.24, -1.143]} scale={0.001} />
        <group name="Box030" position={[-0.429, 1.57, -1.897]} rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <mesh name="Mesh" geometry={nodes.Mesh.geometry} material={materials.Powder_Coated_black} />
          <mesh name="Mesh_1" geometry={nodes.Mesh_1.geometry} material={materials.Glass_Frosted} />
        </group>
        <group name="Cylinder036" position={[-0.531, 1.245, -1.818]} scale={0.001}>
          <mesh name="Mesh154" geometry={nodes.Mesh154.geometry} material={materials.Stainless_Steel_Dull} />
          <mesh name="Mesh154_1" geometry={nodes.Mesh154_1.geometry} material={materials.Powder_Coated_black} />
        </group>
        <mesh name="Object036" geometry={nodes.Object036.geometry} material={materials.PSTRIP_002} position={[-0.61, 1.271, -1.127]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
        <mesh name="DoubleStitch" geometry={nodes.DoubleStitch.geometry} material={materials.Stitch_001} position={[-0.147, 1.416, -2.265]} rotation={[-Math.PI, 0, -2.705]} scale={0.001} />
        <group name="Counter_Top_trim" position={[-0.399, 1.221, -1.115]} scale={0.001}>
          <mesh name="Mesh152" geometry={nodes.Mesh152.geometry} material={materials.P_Stirp_001} />
          <mesh name="Mesh152_1" geometry={nodes.Mesh152_1.geometry} material={materials.PSTRIP_002} />
          <mesh name="Mesh152_2" geometry={nodes.Mesh152_2.geometry} material={materials.PSTRIP_003} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/wireframes/t6.glb')
// Preload the PBR maps so they don't pop in late
useTexture.preload('/maps/floor/Floor_007_Base Color.jpeg')
useTexture.preload('/maps/floor/Floor_007_Normal.jpeg')
useTexture.preload('/maps/floor/Floor_007_Ambient Occlusion.jpeg')
useTexture.preload('/maps/floor/Floor_005_Base Color.jpeg')
useTexture.preload('/maps/floor/Floor_005_Normal.jpeg')
useTexture.preload('/maps/floor/Floor_005_Ambient Occlusion.jpeg')
useTexture.preload('/maps/floor/Floor_008_Base Color.jpeg')
useTexture.preload('/maps/floor/Floor_008_Normal.jpeg')
useTexture.preload('/maps/floor/Floor_008_Ambient Occlusion.jpeg')
